# -*- coding: utf-8 -*-
"""Brain_Tumor_CNN_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPNwNcACi7GvjUO8XxuIb8Kc30QAu8QJ
"""

!pip install tensorflow keras matplotlib opencv-python

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import matplotlib.pyplot as plt
import numpy as np

import os
import shutil
from sklearn.model_selection import train_test_split

train_dir = "/content/brain_tumor_dataset/train"
test_dir = "/content/brain_tumor_dataset/test"

# Create base directory
if not os.path.exists("/content/brain_tumor_dataset"):
    os.makedirs("/content/brain_tumor_dataset")

# Create train and test directories for both classes
os.makedirs(os.path.join(train_dir, "tumor"), exist_ok=True)
os.makedirs(os.path.join(train_dir, "normal"), exist_ok=True)
os.makedirs(os.path.join(test_dir, "tumor"), exist_ok=True)
os.makedirs(os.path.join(test_dir, "normal"), exist_ok=True)

# Get all image files from /content/
all_files = [f for f in os.listdir('/content/') if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))]

tumor_files = []
normal_files = []

for file_name in all_files:
    # Improved logic to classify based on content of filename
    if 'y' in file_name.lower() or 'yes' in file_name.lower():
        tumor_files.append(file_name)
    elif 'n' in file_name.lower() or 'no' in file_name.lower():
        normal_files.append(file_name)

# Initialize empty lists for splits
train_tumor, test_tumor = [], []
train_normal, test_normal = [], []

# Perform split only if there are files in the category
if tumor_files:
    train_tumor, test_tumor = train_test_split(tumor_files, test_size=0.2, random_state=42)
else:
    print("Warning: No 'tumor' images found based on filename pattern (containing 'y' or 'yes').")

if normal_files:
    train_normal, test_normal = train_test_split(normal_files, test_size=0.2, random_state=42)
else:
    print("Warning: No 'normal' images found based on filename pattern (containing 'n' or 'no').")

# Function to move files
def move_files(file_list, destination_folder):
    for file_name in file_list:
        shutil.move(os.path.join('/content/', file_name), destination_folder)

# Move tumor files (only if lists are not empty)
if train_tumor:
    move_files(train_tumor, os.path.join(train_dir, "tumor"))
if test_tumor:
    move_files(test_tumor, os.path.join(test_dir, "tumor"))

# Move normal files (only if lists are not empty)
if train_normal:
    move_files(train_normal, os.path.join(train_dir, "normal"))
if test_normal:
    move_files(test_normal, os.path.join(test_dir, "normal"))

print(f"Dataset organized: {len(train_tumor)} tumor images in train, {len(test_tumor)} tumor images in test.")
print(f"Dataset organized: {len(train_normal)} normal images in train, {len(test_normal)} normal images in test.")

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary'
)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary'
)

model = Sequential()

model.add(Conv2D(32,(3,3),activation='relu',input_shape=(224,224,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1,activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_data,
    epochs=10,
    validation_data=test_data
)

"""# Task
Plot the training and validation accuracy and loss over epochs to analyze the current model's performance and identify potential issues like overfitting or underfitting.

## Plot Training History

### Subtask:
Visualize the training and validation accuracy and loss over the epochs to understand the current model's learning behavior and identify potential overfitting or underfitting.

**Reasoning**:
To visualize the training history, I will extract accuracy and loss values from the `history` object and then use `matplotlib` to plot them in two subplots: one for accuracy and one for loss, with appropriate labels, legends, and a main title.
"""

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(len(acc))

plt.figure(figsize=(12, 4))

# Plotting Accuracy
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training and Validation Accuracy')
plt.legend(loc='lower right')

# Plotting Loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend(loc='upper right')

plt.suptitle('Model Training History', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()

"""## Consider Transfer Learning

### Subtask:
Explore using a pre-trained CNN model (e.g., VGG16, ResNet, InceptionV3) as a base for feature extraction, then fine-tune it on your brain tumor dataset. This often leads to significantly better performance on smaller datasets.

**Reasoning**:
The user wants to implement transfer learning using the VGG16 model. This involves importing VGG16, instantiating it, building a new sequential model, adding the VGG16 base model, freezing its layers, adding custom dense layers for classification, and then compiling the complete model.
"""

from tensorflow.keras.applications.vgg16 import VGG16

# 1. Instantiate the VGG16 model
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# 2. Create a new Sequential model
model_tl = Sequential()

# 3. Add the VGG16 base model
model_tl.add(base_model)

# 4. Freeze the layers of the VGG16 base model
base_model.trainable = False

# 5. Add a Flatten layer
model_tl.add(Flatten())

# 6. Add one or more Dense layers with relu activation
model_tl.add(Dense(128, activation='relu'))
model_tl.add(Dropout(0.5))

# 7. Add a final Dense layer with sigmoid activation for binary classification
model_tl.add(Dense(1, activation='sigmoid'))

# 8. Compile the new model
model_tl.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_tl.summary()
print("Transfer learning model with VGG16 base created and compiled.")

"""**Reasoning**:
The VGG16-based transfer learning model has been created and compiled. The next step is to train this model using the prepared image data generators (`train_data` and `test_data`).


"""

history_tl = model_tl.fit(
    train_data,
    epochs=10,
    validation_data=test_data
)

"""**Reasoning**:
The VGG16-based model has been trained, and now I need to visualize its training history (accuracy and loss) to evaluate its performance, similar to how the initial model's performance was evaluated.


"""

acc_tl = history_tl.history['accuracy']
val_acc_tl = history_tl.history['val_accuracy']
loss_tl = history_tl.history['loss']
val_loss_tl = history_tl.history['val_loss']

epochs_range_tl = range(len(acc_tl))

plt.figure(figsize=(12, 4))

# Plotting Accuracy
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.plot(epochs_range_tl, acc_tl, label='Training Accuracy')
plt.plot(epochs_range_tl, val_acc_tl, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Transfer Learning Model Training and Validation Accuracy')
plt.legend(loc='lower right')

# Plotting Loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.plot(epochs_range_tl, loss_tl, label='Training Loss')
plt.plot(epochs_range_tl, val_loss_tl, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Transfer Learning Model Training and Validation Loss')
plt.legend(loc='upper right')

plt.suptitle('Transfer Learning Model Training History', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()

"""## Implement Advanced Data Augmentation

### Subtask:
Apply more aggressive data augmentation techniques to the training data to increase its diversity and help the model generalize better. This could include more rotation, shifts, brightness changes, etc.

**Reasoning**:
As per the instructions, I need to modify the existing `ImageDataGenerator` for training data to include more aggressive augmentation techniques, and then reinitialize the `train_data` generator with these new parameters.
"""

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40, # Increased from 20
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.3, # Increased from 0.2
    horizontal_flip=True,
    brightness_range=[0.5, 1.5] # Added brightness variation
)

# Note: test_datagen remains the same as no augmentation is applied to test data

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary'
)

print("Advanced data augmentation parameters applied and train_data generator re-created.")

"""## Hyperparameter Tuning

### Subtask:
Adjust hyperparameters such as the learning rate, optimizer, batch size, and dropout rates to find an optimal configuration for the model.

**Reasoning**:
To perform hyperparameter tuning, I will define a new learning rate, create an Adam optimizer with this learning rate, recompile the `model_tl` with the new optimizer, and then retrain the model, storing the training history in `history_tl_tuned`.
"""

from tensorflow.keras.optimizers import Adam

# 1. Define a new learning rate for the Adam optimizer
learning_rate = 0.0001

# 2. Create an instance of the Adam optimizer with the chosen learning rate
optimizer_tuned = Adam(learning_rate=learning_rate)

# 3. Recompile the model_tl using this new optimizer
model_tl.compile(
    optimizer=optimizer_tuned,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print(f"model_tl recompiled with Adam optimizer and learning rate: {learning_rate}")

# 4. Retrain the model_tl for a specified number of epochs
history_tl_tuned = model_tl.fit(
    train_data,
    epochs=10, # Using 10 epochs as a starting point
    validation_data=test_data
)

print("model_tl retrained with tuned hyperparameters.")

"""**Reasoning**:
The `model_tl` has been retrained with tuned hyperparameters. The next step is to visualize its training history (accuracy and loss) to evaluate its performance, similar to how the initial model and the first transfer learning model's performance were evaluated.


"""

from tensorflow.keras.optimizers import Adam

# 1. Define a new learning rate for the Adam optimizer
learning_rate = 0.0001

# 2. Create an instance of the Adam optimizer with the chosen learning rate
optimizer_tuned = Adam(learning_rate=learning_rate)

# 3. Recompile the model_tl using this new optimizer
model_tl.compile(
    optimizer=optimizer_tuned,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print(f"model_tl recompiled with Adam optimizer and learning rate: {learning_rate}")

# 4. Retrain the model_tl for a specified number of epochs
history_tl_tuned = model_tl.fit(
    train_data,
    epochs=10, # Using 10 epochs as a starting point
    validation_data=test_data
)

print("model_tl retrained with tuned hyperparameters.")

# Plotting the training history for the tuned model
acc_tl_tuned = history_tl_tuned.history['accuracy']
val_acc_tl_tuned = history_tl_tuned.history['val_accuracy']
loss_tl_tuned = history_tl_tuned.history['loss']
val_loss_tl_tuned = history_tl_tuned.history['val_loss']

epochs_range_tl_tuned = range(len(acc_tl_tuned))

plt.figure(figsize=(12, 4))

# Plotting Accuracy
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.plot(epochs_range_tl_tuned, acc_tl_tuned, label='Training Accuracy')
plt.plot(epochs_range_tl_tuned, val_acc_tl_tuned, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Tuned Transfer Learning Model Training and Validation Accuracy')
plt.legend(loc='lower right')

# Plotting Loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.plot(epochs_range_tl_tuned, loss_tl_tuned, label='Training Loss')
plt.plot(epochs_range_tl_tuned, val_loss_tl_tuned, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Tuned Transfer Learning Model Training and Validation Loss')
plt.legend(loc='upper right')

plt.suptitle('Tuned Transfer Learning Model Training History', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()

"""## Modify Model Architecture

### Subtask:
Experiment with different CNN architectures, such as adding more convolutional layers, changing the number of filters, or adjusting the dense layer sizes.

**Reasoning**:
To experiment with a different CNN architecture, I will create a new Sequential model, add the frozen VGG16 base, a Flatten layer, two Dense layers with specified units and Dropout rates, and a final Dense layer for binary classification. Then, I will compile this new model with the previously tuned Adam optimizer and print its summary.
"""

model_arch_tuned = Sequential()

# Add the frozen VGG16 base model
model_arch_tuned.add(base_model)

# Add a Flatten layer
model_arch_tuned.add(Flatten())

# Add custom Dense layers with Dropout
model_arch_tuned.add(Dense(256, activation='relu')) # Experiment with 256 units
model_arch_tuned.add(Dropout(0.5)) # Dropout rate 0.5

model_arch_tuned.add(Dense(128, activation='relu')) # Another Dense layer with 128 units
model_arch_tuned.add(Dropout(0.4)) # Dropout rate 0.4

# Add the final Dense layer for binary classification
model_arch_tuned.add(Dense(1, activation='sigmoid'))

# Compile the new model with the tuned learning rate
optimizer_tuned = Adam(learning_rate=0.0001)
model_arch_tuned.compile(
    optimizer=optimizer_tuned,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_arch_tuned.summary()
print("New architecture with modified dense layers created and compiled.")

"""**Reasoning**:
The new model architecture (`model_arch_tuned`) has been defined and compiled. The next step is to train this model using the prepared `train_data` and `test_data` generators to evaluate its performance with the modified architecture.


"""

history_arch_tuned = model_arch_tuned.fit(
    train_data,
    epochs=10,
    validation_data=test_data
)

print("model_arch_tuned trained with new architecture.")

"""**Reasoning**:
The `model_arch_tuned` has been trained, and now I need to visualize its training history (accuracy and loss) to evaluate its performance, similar to how the previous models' performances were evaluated.


"""

acc_arch_tuned = history_arch_tuned.history['accuracy']
val_acc_arch_tuned = history_arch_tuned.history['val_accuracy']
loss_arch_tuned = history_arch_tuned.history['loss']
val_loss_arch_tuned = history_arch_tuned.history['val_loss']

epochs_range_arch_tuned = range(len(acc_arch_tuned))

plt.figure(figsize=(12, 4))

# Plotting Accuracy
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.plot(epochs_range_arch_tuned, acc_arch_tuned, label='Training Accuracy')
plt.plot(epochs_range_arch_tuned, val_acc_arch_tuned, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Modified Architecture Model Training and Validation Accuracy')
plt.legend(loc='lower right')

# Plotting Loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.plot(epochs_range_arch_tuned, loss_arch_tuned, label='Training Loss')
plt.plot(epochs_range_arch_tuned, val_loss_arch_tuned, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Modified Architecture Model Training and Validation Loss')
plt.legend(loc='upper right')

plt.suptitle('Modified Architecture Model Training History', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()

"""## Implement Callbacks for Training

### Subtask:
Add callbacks like EarlyStopping to prevent overfitting and ModelCheckpoint to save the best performing model during training based on validation accuracy or loss.

**Reasoning**:
To implement callbacks for training, I will first import EarlyStopping and ModelCheckpoint, then instantiate them with the specified parameters, and finally retrain the `model_arch_tuned` model using these callbacks.
"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# 1. Instantiate EarlyStopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# 2. Instantiate ModelCheckpoint callback
model_checkpoint = ModelCheckpoint(
    filepath='best_model.keras',
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

print("EarlyStopping and ModelCheckpoint callbacks instantiated.")

# 3. Retrain the model_arch_tuned model with callbacks
history_callbacks = model_arch_tuned.fit(
    train_data,
    epochs=30, # Increased epochs to allow callbacks to work effectively
    validation_data=test_data,
    callbacks=[early_stopping, model_checkpoint]
)

print("model_arch_tuned trained with EarlyStopping and ModelCheckpoint callbacks.")

"""**Reasoning**:
The `model_arch_tuned` has been trained with callbacks, and now I need to visualize its training history (accuracy and loss) to evaluate its performance, similar to how the previous models' performances were evaluated.


"""

acc_callbacks = history_callbacks.history['accuracy']
val_acc_callbacks = history_callbacks.history['val_accuracy']
loss_callbacks = history_callbacks.history['loss']
val_loss_callbacks = history_callbacks.history['val_loss']

epochs_range_callbacks = range(len(acc_callbacks))

plt.figure(figsize=(12, 4))

# Plotting Accuracy
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
plt.plot(epochs_range_callbacks, acc_callbacks, label='Training Accuracy')
plt.plot(epochs_range_callbacks, val_acc_callbacks, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Callbacks Model Training and Validation Accuracy')
plt.legend(loc='lower right')

# Plotting Loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
plt.plot(epochs_range_callbacks, loss_callbacks, label='Training Loss')
plt.plot(epochs_range_callbacks, val_loss_callbacks, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Callbacks Model Training and Validation Loss')
plt.legend(loc='upper right')

plt.suptitle('Callbacks Model Training History', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to make space for suptitle
plt.show()

"""## Retrain and Evaluate Best Model

### Subtask:
Retrain the model with the chosen improvements (e.g., transfer learning, new architecture, tuned hyperparameters, callbacks) and thoroughly evaluate its performance on the test set, including generating a classification report and confusion matrix.

## Retrain and Evaluate Best Model

### Subtask:
Retrain the model with the chosen improvements (e.g., transfer learning, new architecture, tuned hyperparameters, callbacks) and thoroughly evaluate its performance on the test set, including generating a classification report and confusion matrix.

#### Instructions
1. Load the best model saved as 'best_model.keras' using `tf.keras.models.load_model()`.
2. Evaluate the loaded best model on the `test_data` to get the test loss and accuracy using the `.evaluate()` method. Print these results.
3. Obtain the predicted probabilities for the `test_data` using the `.predict()` method of the loaded model. Make sure to reset the `test_data` generator before prediction to ensure the correct order of images.
4. Convert the predicted probabilities into binary class labels (0 or 1) by applying a threshold (e.g., 0.5).
5. Get the true class labels from the `test_data` generator. You can access these using `test_data.classes` and ensure the order matches the predictions.
6. Generate a classification report using `sklearn.metrics.classification_report`, passing the true labels and predicted labels. Print the report.
7. Generate a confusion matrix using `sklearn.metrics.confusion_matrix`, passing the true labels and predicted labels. Print the matrix.
8. Import `seaborn` as `sns` and `matplotlib.pyplot` as `plt`. Create a heatmap of the confusion matrix using `sns.heatmap()` for better visualization. Add appropriate labels, title, and display the plot.

## Retrain and Evaluate Best Model

### Subtask:
Retrain the model with the chosen improvements (e.g., transfer learning, new architecture, tuned hyperparameters, callbacks) and thoroughly evaluate its performance on the test set, including generating a classification report and confusion matrix.

#### Instructions
1. Load the best model saved as 'best_model.keras' using `tf.keras.models.load_model()`.
2. Evaluate the loaded best model on the `test_data` to get the test loss and accuracy using the `.evaluate()` method. Print these results.
3. Obtain the predicted probabilities for the `test_data` using the `.predict()` method of the loaded model. Make sure to reset the `test_data` generator before prediction to ensure the correct order of images.
4. Convert the predicted probabilities into binary class labels (0 or 1) by applying a threshold (e.g., 0.5).
5. Get the true class labels from the `test_data` generator. You can access these using `test_data.classes` and ensure the order matches the predictions.
6. Generate a classification report using `sklearn.metrics.classification_report`, passing the true labels and predicted labels.
7. Generate a confusion matrix using `sklearn.metrics.confusion_matrix`, passing the true labels and predicted labels.
8. Import `seaborn` as `sns` and `matplotlib.pyplot` as `plt`. Create a heatmap of the confusion matrix using `sns.heatmap()` for better visualization. Add appropriate labels, title, and display the plot.

**Reasoning**:
The next logical step is to load the best model saved as 'best_model.keras' as per the first instruction of the subtask.
"""

import tensorflow as tf

# 1. Load the best model
best_model = tf.keras.models.load_model('best_model.keras')

print("Best model 'best_model.keras' loaded successfully.")

"""**Reasoning**:
Following the instructions, the next step is to evaluate the loaded best model on the test data to obtain and print its loss and accuracy.


"""

loss, accuracy = best_model.evaluate(test_data)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

"""**Reasoning**:
Following the instructions, the next step is to obtain predicted probabilities for the test data and ensure the generator is reset to maintain correct order.


"""

test_data.reset()
predictions = best_model.predict(test_data)
print("Predicted probabilities obtained.")

"""**Reasoning**:
As per the instructions, the next step is to convert the predicted probabilities into binary class labels using a threshold of 0.5.


"""

predicted_labels = (predictions > 0.5).astype(int)
print("Predicted probabilities converted to binary labels.")

"""**Reasoning**:
As per the instructions, the next step is to get the true class labels from the `test_data` generator.


"""

true_labels = test_data.classes
print("True class labels obtained.")

"""**Reasoning**:
Following the instructions, the next step is to generate a classification report using `sklearn.metrics.classification_report` and print it.


"""

from sklearn.metrics import classification_report

report = classification_report(true_labels, predicted_labels)
print("Classification Report:")
print(report)

"""**Reasoning**:
Following the instructions, the next step is to generate a confusion matrix using `sklearn.metrics.confusion_matrix` and print it.


"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:")
print(cm)

"""**Reasoning**:
As per the instructions, the final step is to import `seaborn` and `matplotlib.pyplot`, then create a heatmap of the confusion matrix for better visualization, adding appropriate labels and a title.


"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted Negative', 'Predicted Positive'],
            yticklabels=['Actual Negative', 'Actual Positive'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix Heatmap')
plt.show()
print("Confusion matrix heatmap displayed.")

"""## Summary:

### Q&A
The initial task asked to analyze the current model's performance and identify potential issues like overfitting or underfitting. Through the solving process, it was found that the initial VGG16-based transfer learning model showed good learning behavior. However, subsequent evaluations of the fine-tuned model revealed a significant issue: the model completely failed to classify one of the classes.

### Data Analysis Key Findings
*   **Initial Transfer Learning Performance:** A VGG16-based model, with its base layers frozen and new dense layers added, was trained. Over 10 epochs, training accuracy improved from approximately 51.2% to 84.94%, and validation accuracy increased from 29.27% to 85.37%. Correspondingly, training loss decreased from 1.93 to 0.3175, and validation loss decreased from 1.44 to 0.2710.
*   **Advanced Data Augmentation:** More aggressive data augmentation techniques were applied, including increased `rotation_range` (to 40), `zoom_range` (to 0.3), and the addition of `width_shift_range`, `height_shift_range`, `shear_range`, and `brightness_range`.
*   **Hyperparameter Tuning (Learning Rate):** The Adam optimizer's learning rate was tuned to 0.0001. After retraining for 10 epochs with this new learning rate, the model achieved approximately 80% training accuracy and 93% validation accuracy, with training loss around 0.43 and validation loss around 0.28.
*   **Modified Model Architecture:** The architecture of the custom dense layers was changed to include a `Dense` layer with 256 units (with 0.5 dropout) and another `Dense` layer with 128 units (with 0.4 dropout). During training for 10 epochs, the training accuracy reached about 72.88%, but the validation accuracy remained stagnant at 75.61% across all epochs, despite a decrease in validation loss from 0.7721 to 0.4206.
*   **Callbacks Implementation:** `EarlyStopping` (monitoring `val_loss` with patience 5) and `ModelCheckpoint` (monitoring `val_accuracy`) were implemented. The model was retrained for up to 30 epochs, and the best model was saved based on validation accuracy, which reached 78.049% at Epoch 4.
*   **Final Model Evaluation:** The best saved model achieved a Test Loss of 0.3997 and a Test Accuracy of 0.7805.
    *   **Severe Class Imbalance Issue:** The classification report revealed that for Class 0 (Negative), the precision, recall, and f1-score were all 0.00. This is confirmed by the confusion matrix which shows 0 True Negatives and 10 False Positives.
    *   **Strong Performance on Class 1:** For Class 1 (Positive), the model demonstrated good performance with a precision of 0.75, recall of 0.97, and f1-score of 0.85, correctly identifying 30 out of 31 instances (30 True Positives, 1 False Negative).
    *   The model completely failed to classify any instance of Class 0 correctly, indicating a significant bias towards Class 1.

### Insights or Next Steps
*   The model exhibits a severe bias towards predicting the positive class (Class 1), completely failing to identify any instances of the negative class (Class 0). This suggests a strong class imbalance problem or insufficient feature learning for the negative class.
*   Implement strategies to address the class imbalance, such as weighted loss functions, oversampling the minority class (e.g., using SMOTE), or undersampling the majority class. Re-evaluate the model's performance using metrics more robust to imbalance, like the F1-score for each class.

**Reasoning**:
The previous cell failed because the `streamlit` library was not found. To fix this, I need to install it using `!pip install` before importing it.

**Reasoning**:
The `streamlit` library has been successfully installed. Now, I can proceed with importing all the necessary libraries for the Streamlit application as originally intended by the subtask.
"""

import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Ensure the model is loaded (from previous steps)
# If running this cell independently, ensure 'best_model' and 'train_dir', 'test_dir' are defined.
# For example:
# from tensorflow.keras.models import load_model
# best_model = load_model('best_model.keras')
# train_dir = "/content/brain_tumor_dataset/train"
# test_dir = "/content/brain_tumor_dataset/test"

# Get lists of image files from train and test directories
all_train_images = []
for class_name in os.listdir(train_dir):
    class_path = os.path.join(train_dir, class_name)
    if os.path.isdir(class_path):
        for fname in os.listdir(class_path):
            all_train_images.append(os.path.join(class_path, fname))

all_test_images = []
for class_name in os.listdir(test_dir):
    class_path = os.path.join(test_dir, class_name)
    if os.path.isdir(class_path):
        for fname in os.listdir(class_path):
            all_test_images.append(os.path.join(class_path, fname))

all_images = all_train_images + all_test_images

# Randomly select one image
if all_images:
    random_image_path = random.choice(all_images)
    print(f"Randomly selected image: {random_image_path}")

    # Load and preprocess the image
    image = cv2.imread(random_image_path)
    if image is None:
        print(f"Error: Could not load image from {random_image_path}")
    else:
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image_to_predict = cv2.resize(image, (224, 224))
        image_to_predict = np.expand_dims(image_to_predict, axis=0) / 255.0

        # Make prediction
        prediction = best_model.predict(image_to_predict)

        # Interpret prediction
        if prediction[0][0] > 0.5:
            result = 'Tumor'
        else:
            result = 'Not a Tumor'

        # Display the image and prediction
        plt.figure(figsize=(6, 6))
        plt.imshow(image_rgb)
        plt.title(f"Prediction: {result} (Confidence: {prediction[0][0]:.4f})")
        plt.axis('off')
        plt.show()
else:
    print("No images found in the dataset directories.")

"""# Task
Save the `model_arch_tuned` as `brain_tumor_model.h5` and update the `app.py` script to load `brain_tumor_model.h5` using `tf.keras.models.load_model` instead of the TFLite interpreter.

## Save Model as .h5

### Subtask:
Save the `model_arch_tuned` (which is the current best Keras model) into the `.h5` format as `brain_tumor_model.h5`. This will create a deployable Keras model file.

**Reasoning**:
As per the instructions, I need to save the `model_arch_tuned` Keras model into the `.h5` format.
"""

model_arch_tuned.save('brain_tumor_model.h5')
print("Model 'brain_tumor_model.h5' saved successfully.")

"""**Reasoning**:
The model has been successfully saved as 'brain_tumor_model.h5'. The next step, as per the overall task, is to update the `app.py` script to load this `.h5` model instead of the TFLite interpreter.

## Final Task

### Subtask:
Confirm that the model has been saved in `.h5` format and `app.py` has been updated to load it correctly, ready for Streamlit deployment.

## Summary:

### Q&A
*   **Confirm that the model has been saved in `.h5` format and `app.py` has been updated to load it correctly, ready for Streamlit deployment.**
    Yes, the `model_arch_tuned` was saved as `brain_tumor_model.h5`, and the `app.py` script was updated to load this Keras model correctly using `tf.keras.models.load_model()`, ready for Streamlit deployment.

### Data Analysis Key Findings
*   The `model_arch_tuned` Keras model was successfully saved to `brain_tumor_model.h5`.
*   The `app.py` script was updated to load `brain_tumor_model.h5` using `tf.keras.models.load_model()` within a cached function, ensuring efficient model loading for the Streamlit application.
*   The updated `app.py` script includes functionality for users to select an image, display it, and trigger a prediction using the loaded Keras model, classifying it as "Tumor" or "Not a Tumor" with a reported confidence score.

### Insights or Next Steps
*   The current solution uses the HDF5 (`.h5`) format, but TensorFlow issued a warning recommending the native Keras format (`.keras`). Consider migrating to the `.keras` format for future model saving to leverage the latest features and best practices.
*   The updated `app.py` is ready for Streamlit deployment, allowing users to interact with the brain tumor detection model through a web interface. The next step would be to deploy this `app.py` script.

# Task
Analyze the characteristics of the brain MRI image dataset, specifically focusing on the class distribution (tumor vs. normal images) for both training and testing sets. Based on this analysis, articulate the identified class imbalance and propose a detailed data preparation strategy, providing a rationale for chosen techniques like oversampling (e.g., SMOTE) or class weighting to mitigate its impact.

## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Analyze the characteristics of the brain MRI image dataset (e.g., size, class distribution, image dimensions). Based on this analysis, prepare a detailed data preparation strategy, providing rationale and justification for each step, especially regarding class imbalance.

## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Analyze the characteristics of the brain MRI image dataset (e.g., size, class distribution, image dimensions). Based on this analysis, prepare a detailed data preparation strategy, providing rationale and justification for each step, especially regarding class imbalance.

#### Instructions
1. Count the number of 'tumor' and 'normal' images in the `train_dir` to determine the class distribution for the training set. Display these counts.
2. Count the number of 'tumor' and 'normal' images in the `test_dir` to determine the class distribution for the testing set. Display these counts.
3. Calculate and display the percentage of 'tumor' and 'normal' images for both the training and testing sets.
4. Articulate the observed class distribution for both sets and explicitly state if a class imbalance is present. If so, describe the nature and extent of this imbalance.
5. Propose a detailed data preparation strategy to address the identified class imbalance, providing a rationale for each chosen technique (e.g., oversampling with SMOTE, class weighting, or other relevant methods).

## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Analyze the characteristics of the brain MRI image dataset (e.g., size, class distribution, image dimensions). Based on this analysis, prepare a detailed data preparation strategy, providing rationale and justification for each step, especially regarding class imbalance.

#### Instructions
1. Count the number of 'tumor' and 'normal' images in the `train_dir` to determine the class distribution for the training set. Display these counts.
2. Count the number of 'tumor' and 'normal' images in the `test_dir` to determine the class distribution for the testing set. Display these counts.
3. Calculate and display the percentage of 'tumor' and 'normal' images for both the training and testing sets.
4. Articulate the observed class distribution for both sets and explicitly state if a class imbalance is present. If so, describe the nature and extent of this imbalance.
5. Propose a detailed data preparation strategy to address the identified class imbalance, providing a rationale for each chosen technique (e.g., oversampling with SMOTE, class weighting, or other relevant methods).

```markdown
## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Analyze the characteristics of the brain MRI image dataset (e.g., size, class distribution, image dimensions). Based on this analysis, prepare a detailed data preparation strategy, providing rationale and justification for each step, especially regarding class imbalance.

#### Instructions
1. Count the number of 'tumor' and 'normal' images in the `train_dir` to determine the class distribution for the training set. Display these counts.
2. Count the number of 'tumor' and 'normal' images in the `test_dir` to determine the class distribution for the testing set. Display these counts.
3. Calculate and display the percentage of 'tumor' and 'normal' images for both the training and testing sets.
4. Articulate the observed class distribution for both sets and explicitly state if a class imbalance is present. If so, describe the nature and extent of this imbalance.
5. Propose a detailed data preparation strategy to address the identified class imbalance, providing a rationale for each chosen technique (e.g., oversampling with SMOTE, class weighting, or other relevant methods).
```

**Reasoning**:
As per the instructions, the first step is to count the number of 'tumor' and 'normal' images in the `train_dir` to determine the class distribution for the training set. This involves iterating through the subdirectories of `train_dir` and counting the files in each.
"""

import os

train_tumor_count = len(os.listdir(os.path.join(train_dir, 'tumor')))
train_normal_count = len(os.listdir(os.path.join(train_dir, 'normal')))

print(f"Training set - Tumor images: {train_tumor_count}")
print(f"Training set - Normal images: {train_normal_count}")

"""# Task
## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Count the number of 'tumor' and 'normal' images in the `test_dir` to determine the class distribution for the testing set. Display these counts.

**Reasoning**:
Following the analysis of the training set, the next step is to count the 'tumor' and 'normal' images within the `test_dir` to understand the class distribution for the testing dataset. This will involve iterating through the subdirectories of `test_dir` and counting the number of files in each.

## Count Test Set Images

### Subtask:
Count the number of 'tumor' and 'normal' images in the `test_dir` to determine the class distribution for the testing set. Display these counts.

**Reasoning**:
As per the instructions, the next step is to count the number of 'tumor' and 'normal' images in the `test_dir` to determine the class distribution for the testing set and display these counts.
"""

test_tumor_count = len(os.listdir(os.path.join(test_dir, 'tumor')))
test_normal_count = len(os.listdir(os.path.join(test_dir, 'normal')))

print(f"Testing set - Tumor images: {test_tumor_count}")
print(f"Testing set - Normal images: {test_normal_count}")

"""# Task
## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Calculate and display the percentage of 'tumor' and 'normal' images for both the training and testing sets.

**Reasoning**:
Having counted the 'tumor' and 'normal' images in both the training and testing directories, the next logical step is to calculate their respective percentages to get a clearer understanding of the class distribution. This will help quantify the extent of any class imbalance before articulating its implications and proposing solutions.

## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Calculate and display the percentage of 'tumor' and 'normal' images for both the training and testing sets.

## Analyze Data Characteristics and Prepare Strategy

### Subtask:
Calculate and display the percentage of 'tumor' and 'normal' images for both the training and testing sets.

#### Instructions
1. Calculate the total number of images in the training set by adding `train_tumor_count` and `train_normal_count`.
2. Calculate the percentage of 'tumor' and 'normal' images in the training set using their respective counts and the total training images. Display these percentages.
3. Calculate the total number of images in the testing set by adding `test_tumor_count` and `test_normal_count`.
4. Calculate the percentage of 'tumor' and 'normal' images in the testing set using their respective counts and the total testing images. Display these percentages.

**Reasoning**:
As per the instructions, I need to calculate the percentages of tumor and normal images for both the training and testing sets and display them.
"""

total_train_images = train_tumor_count + train_normal_count
perc_train_tumor = (train_tumor_count / total_train_images) * 100
perc_train_normal = (train_normal_count / total_train_images) * 100

print(f"Training set - Tumor images percentage: {perc_train_tumor:.2f}%")
print(f"Training set - Normal images percentage: {perc_train_normal:.2f}%")

total_test_images = test_tumor_count + test_normal_count
perc_test_tumor = (test_tumor_count / total_test_images) * 100
perc_test_normal = (test_normal_count / total_test_images) * 100

print(f"Testing set - Tumor images percentage: {perc_test_tumor:.2f}%")
print(f"Testing set - Normal images percentage: {perc_test_normal:.2f}%")